### ISSUE TITLE
Tracking issue for DSLs

### ISSUE THREAD

**Issue by nanaian** [pmret/papermario#368]
Known DSLs we need macros and disassemblers for:

- [x] si scripts (evt)
- [ ] sparkle scripts
- [x] hud element animations (AKA icon scripts)
- [ ] entity scripts
- [ ] entity model scripts
- [ ] item entity scripts
- [ ] model animations
- [ ] sprite animations (supported in star rod xml, icky)

...this game is ridiculous

**Comment by nanaian** [comment]
Now we've renamed ScriptInstance to Evt it may be worth renaming all the `si` funcs to `evt` (and even matching the TTYD opcode names).

**Comment by nanaian** [comment]
Considering getting rid of cc_dsl in favour of simple macros
```c
EvtSource script = {
    evt_ifgt(SI_VAR(0), 0)
        evt_call(SetPlayerPos, 0, SI_VAR(0), 0),
    evt_endif,
    evt_return,
    evt_end,
};
```
